version: 2

sources:
  - name: olist_raw
    schema: RAW
    freshness:
      warn_after:
        count: 12
        period: hour
      error_after:
        count: 24
        period: hour
    tables:
      - name: customers
        identifier: customers
        loaded_at_field: customer_id
      - name: orders
        identifier: orders
        loaded_at_field: order_purchase_timestamp
      - name: order_items
        identifier: order_items
        loaded_at_field: order_id
      - name: products
        identifier: products
      - name: payments
        identifier: payments
      - name: product_categories
        identifier: product_categories 